name: API Promotion Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # เพิ่มอันนี้ไว้ให้กดรันแบบ Manual ได้ด้วยเวลาอยากทดสอบ

jobs:
  promote-to-nonprod:
    runs-on: ubuntu-latest
    environment: non-prod
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     # 1. ยิง API ไปสั่ง Dev ให้ Export
      - name: Export API Archive from DEV
        run: |
          curl -fS -X POST "http://${{ secrets.HOST_DEV }}:5555/rest/apigateway/archives/export" \
            -u "${{ secrets.DEV_USERNAME }}:${{ secrets.DEV_PASSWORD }}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/zip" \
            -d '{
                  "apis": [{"apiName": "My_FastAPI", "apiVersion": "1.0"}]
                }' \
            --output api_archive.zip

      # แทรก Step นี้เพื่อดูว่าข้างในไฟล์ zip (ที่โหลดมา 78 bytes) เขียนว่าอะไร
      - name: Check Error Message
        if: failure() # ทำงานเฉพาะเมื่อขั้นตอนก่อนหน้าพัง
        run: cat api_archive.zip

      # 2. นำไฟล์ ไป Import
      - name: Import API Archive to NON-PROD
        run: |
          curl -fS -X POST "http://${{ secrets.HOST_NONPROD }}:5555/rest/apigateway/archives/import" \
            -u "${{ secrets.NONPROD_USERNAME }}:${{ secrets.NONPROD_PASSWORD }}" \
            -F "file=@api_archive.zip"